name: notepod
base: core22
version: '1.0.0'
summary: Privacy preserving note taking app using PODs.
description: |
  Notepod is a note taking app, storing your notes within your Solid
  Pod. Make notes anywhere, anytime, on any device and review them
  later on. Great for that bush walk where you've suddenly come up
  with a great idea you don't want to lose, or sharing the shopping
  list with the family so whoever is next at the shops has it at their
  finger tips.

grade: stable
confinement: strict

apps:
  notepod:
    command: notepod
    extensions: [desktop-gtk3]
    plugs:
      - network
      - home

parts:
  notepod:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
